function List = weiList(act, varargin)
% Obtain list of Weizmann sequences grouped by action.
%
% Input
%   act     -  act name, 'walk' | 'side' | 'skip' | 'run' | 'jack' | 'jump' | 'pjump' | 'wave1' | 'wave2' | 'bend'
%   varargin
%     ran   -  flag of using range, {'y'} | 'n'
%
% Output
%   List    -  list of sequences, n x 4
%
% History
%   create  -  Feng Zhou (zhfe99@gmail.com), 09-02-2010
%   modify  -  Feng Zhou (zhfe99@gmail.com), 10-09-2011

% function option
isRan = psY(varargin, 'ran', 'y');

% walk
if strcmp(act, 'walk')
    List = {'daria', 'walk', 'normal', [4 43]; ...
            'denis', 'walk', 'normal', [14 54]; ...
            'eli', 'walk', 'normal', [23 66]; ...
            'ido', 'walk', 'normal', []; ...
            'ira', 'walk', 'normal', [22 66]; ...
            'lena', 'walk', 'normal', [24 66]; ...
            'lyova', 'walk', 'normal', [1 43]; ...
            'moshe', 'walk', 'normal', [9 48]; ...
            'shahar', 'walk', 'normal', [20 62]};
    
% run
elseif strcmp(act, 'run')
    List = {'daria', 'run', 'normal', [10 37]; ...
            'denis', 'run', 'normal', [7 35]; ...
            'eli', 'run', 'normal', [9 44]; ...
            'ido', 'run', 'normal', [2 32]; ...
            'ira', 'run', 'normal', [14 44]; ...
            'lena', 'run', 'normal', []; ...
            'lyova', 'run', 'normal', [2 33]; ...
            'moshe', 'run', 'normal', [8 38]};

% jump
elseif strcmp(act, 'jump')
    List = {'daria', 'jump', 'normal', [8 42]; ...
            'denis', 'jump', 'normal', [12 49]; ...
            'eli', 'jump', 'normal', []; ...
            'ido', 'jump', 'normal', [1 43]; ...
            'ira', 'jump', 'normal', [9 45]; ...
            'lena', 'jump', 'normal', [1 39]; ...
            'lyova', 'jump', 'normal', [5 39]; ...
            'moshe', 'jump', 'normal', []};

% wave1
elseif strcmp(act, 'wave1')
    List = {'daria', 'wave1', 'normal', [8 42]; ...
            'denis', 'wave1', 'normal', [12 49]; ...
            'eli', 'wave1', 'normal', []; ...
            'ido', 'wave1', 'normal', [1 43]; ...
            'ira', 'wave1', 'normal', [9 45]; ...
            'lena', 'wave1', 'normal', [1 39]; ...
            'lyova', 'wave1', 'normal', [5 39]; ...
            'moshe', 'wave1', 'normal', []};

% jack
elseif strcmp(act, 'jack')
    List = {'eli', 'jack', 'normal', [1 28]; ... % 1-cycle
            'eli', 'jack', 'normal', [1 51]; ... % 2-cycle
            'daria', 'jack', 'normal', [1 58]};

else
    error('unknown act: %s', act);
end

% remove range
if ~isRan
    for i = 1 : size(List, 1)
        List{i, 4} = [];
    end
end
