function nms = joinSet(setNm)
% Obtain all joint names belonging to a specific joint set.
%
% Input
%   setNm   -  joint set name, 'barbic' | 'leg' | 'hand' | 'all_cmu' | 'all_kit' | 'kitchen' | 'arm'
%              'barbic'   -  See: http://graphics.cs.cmu.edu/projects/segmentation
%              'arm'      -  right arm
%              'all_cmu'  -  all 29 joints for CMU motion capture database, See: http://mocap.cs.cmu.edu
%              'all_kit'  -  all 29 joints for CMU motion capture database, See: http://kitchen.cs.cmu.edu
%              'kitchen'  -  arm+leg+torso
%
% Output
%   nms     -  joint names, 1 x nJ (cell)
%
% History
%   create  -  Feng Zhou (zhfe99@gmail.com), 12-29-2008
%   modify  -  Feng Zhou (zhfe99@gmail.com), 03-01-2013

% 14 discriminative joints for CMU motion capture
if strcmp(setNm, 'barbic')
    nms = {'lowerback', ...
           'upperback', ...
           'thorax', ...
           'lowerneck', ...
           'upperneck', ...
           'head', ...
           'rhumerus', ...
           'rradius', ...
           'lhumerus', ...
           'lradius', ...
           'rfemur', ...
           'rtibia', ...
           'lfemur', ...
           'ltibia'};

elseif strcmp(setNm, 'leg')
    nms = {'lhumerus', 'rhumerus', ...,
           'lwrist', 'rwrist', ...
           'lfemur', 'rfemur', ...
           'ltibia', 'rtibia'};

elseif strcmp(setNm, 'hand')
    nms = {'lowerback', 'upperback', ...
           'lhand', 'rhand', ...
           'lradius', 'rradius'};         

% all 29 joints for CMU motion capture database
elseif strcmp(setNm, 'all_cmu')
    nms = {'root', ...
           'lowerback', ...
           'upperback', ...
           'thorax', ...
           'lowerneck', ...
           'upperneck', ...
           'head', ...
           'rclavicle', ...
           'rhumerus', ...
           'rradius', ...
           'rwrist', ...
           'rhand', ...
           'rfingers', ...
           'rthumb', ...
           'lclavicle', ...
           'lhumerus', ...
           'lradius', ...
           'lwrist', ...
           'lhand', ...
           'lfingers', ...
           'lthumb', ...
           'rfemur', ...
           'rtibia', ...
           'rfoot', ...
           'rtoes', ...
           'lfemur', ...
           'ltibia', ...
           'lfoot', ...
           'ltoes'};
    
elseif strcmp(setNm, 'all_cmu2')
    nms = {'root', ...
           'lhipjoint', ...
           'lfemur', ...
           'ltibia', ...
           'lfoot', ...
           'ltoes', ...
           'rhipjoint', ...
           'rfemur', ...
           'rtibia', ...
           'rfoot', ...
           'rtoes', ...
           'lowerback', ...
           'upperback', ...
           'thorax', ...
           'lowerneck', ...
           'upperneck', ...
           'head', ...
           'lclavicle', ...
           'lhumerus', ...
           'lradius', ...
           'lwrist', ...
           'lhand', ...
           'lfingers', ...
           'lthumb', ...
           'rclavicle', ...
           'rhumerus', ...
           'rradius', ...
           'rwrist', ...
           'rhand', ...
           'rfingers', ...
           'rthumb'};

% all joints for Kitchen motion capture database
elseif strcmp(setNm, 'all_kit')
    nms = {'pelvis', ...
           'lfemur', ...
           'ltibia', ...
           'lfoot', ...
           'ltoes', ...
           'rfemur', ...
           'rtibia', ...
           'rfoot', ...
           'rtoes', ...
           'lowerback', ...
           'upperback', ...
           'lclavicle', ...
           'lhumerus', ...
           'lradius', ...
           'lhand', ...
           'rclavicle', ...
           'rhumerus', ...
           'rradius', ...
           'rhand', ...
           'neck'};

elseif strcmp(setNm, 'kitchen')
    nms = {'lowerback', ...
           'lhumerus', ...
           'lradius', ...
           'lfemur', ...
           'rhumerus', ...
           'rfemur', ...
           'rradius'};
        
elseif strcmp(setNm, 'arm_hand')
    nms = {'lowerback', 'upperback', ...
           'lhand', 'rhand', ...
           'lradius', 'rradius', ...
           'lhumerus', 'rhumerus'};%, ...
            % 'lhumerus', 'lradius'
            %'rhand', 'lhand', ...};
    
elseif strcmp(setNm, 'rarm')
    nms = {'rhumerus', ...
           'rradius'};%, ...
            % 'lhumerus', 'lradius'
            %'rhand', 'lhand', ...};
    
else
    error('unknown joint set name: %s', setNm);
end
